/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TemplateCard from "./TemplateCard";

const templateData = [
  {
    title: "Wedding Invitations",
    description: "Cream Green Simple Wedding Invitation",
    iconSrc:
      "https://marketplace.canva.com/EAF5QptOGfM/2/0/1143w/canva-WoFLXrCHcbY.jpg",
  },
  {
    title: "Birthday Invitations",
    description: "Black and Gold Elegant Metallic Botanicals",
    iconSrc:
      "https://marketplace.canva.com/EAFbFT5w3oQ/1/0/286w/canva--tpYyzJFNBc.jpg",
  },
  {
    title: "Wedding Invitation",
    description: "Cream Green Simple Illustrated Wedding Invitation",
    iconSrc:
      "https://marketplace.canva.com/EAF5o4uDCM4/1/0/286w/canva-kl6owQ45DJc.jpg",
  },
  {
    title: "Wedding Invitation",
    description: "Cream Green Simple Illustrated Wedding Invitation",
    iconSrc:
      "https://marketplace.canva.com/EAFuVSmbOZk/2/0/286w/canva-RlD5JS4PtOk.jpg",
  },
];

function DiscoverTemplates() {
  return (
    <main className="flex overflow-hidden gap-2.5 items-start py-24">
      <section className="flex overflow-hidden flex-col flex-1 shrink items-start py-24 px-12 w-full rounded-3xl basis-0 bg-slate-50 ">
        <div className="flex flex-col items-start max-w-full font-bold text-black w-[1240px]">
          <h1 className="gap-2.5 text-5xl leading-tight max-md:max-w-full max-md:text-4xl">
            Discover Templates
          </h1>
          <p className="gap-2.5 font-normal self-stretch mt-4 w-full text-lg leading-6 max-md:max-w-full">
            Choose from a range of professionally designed templates for various
            occasions. Easily personalize these templates with your own text,
            images, and colors to perfectly match your event.
          </p>
          <button className="gap-2.5 px-6 py-4 mt-4 text-base text-white bg-blue-500 rounded-full max-md:px-5">
            Explore more
          </button>
        </div>
        <div className="flex mt-10 min-h-[60px] w-[60px]" aria-hidden="true" />
        <div className="flex flex-col mt-10 max-md:max-w-full">
          <div className="flex overflow-hidden gap-6 items-start max-md:max-w-full">
            {templateData.map((template, index) => (
              <TemplateCard
                key={index}
                title={template.title}
                description={template.description}
                iconSrc={template.iconSrc}
              />
            ))}
          </div>
          <nav className="flex gap-6 items-start self-start mt-10">
            <button aria-label="Previous page">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/e8f5e8a001a7ffd47177431ce572ac094ebf421c1d758ca805443838471893e4?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca"
                alt=""
                className="object-contain shrink-0 w-6 aspect-square"
              />
            </button>
            <button aria-label="Next page">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/ab9581acf921bd604bf7bf7dc169fcb9dfde81245fb9f9e425d3f5875d13e225?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca"
                alt=""
                className="object-contain shrink-0 w-6 aspect-square"
              />
            </button>
          </nav>
        </div>
      </section>
    </main>
  );
}

export default DiscoverTemplates;
