/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { ArrowRightCircle } from "lucide-react";
function TemplateCard({ title, description, iconSrc }) {
  return (
    <article
      className="rounded-3xl flex overflow-hidden flex-col justify-center p-6 bg-no-repeat bg-cover min-h-[400px] min-w-[340px] w-[436px] w-full max-md:px-5 max-md:max-w-full"
      style={{ backgroundImage: `url(${iconSrc})` }}
    >
      <div className="flex flex-col justify-between flex-1 w-full">
        <div className="flex flex-col flex-1 w-full text-black z-10">
          <div className="flex overflow-hidden flex-col justify-center p-4 w-full bg-white rounded-3xl z-10">
            <h2 className="text-lg font-medium leading-tight">{title}</h2>
            <p className="mt-2 text-base leading-none">{description}</p>
          </div>
        </div>
        <div className="p-3 bg-blue-500 self-end rounded-full">
          <ArrowRightCircle color="white" />
        </div>
      </div>
    </article>
  );
}

export default TemplateCard;
