/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import MainContent from "./MainContent";
import ImageSection from "./ImageSection";

function GetStarted() {
  return (
    <main className="flex overflow-hidden relative flex-col justify-center px-48 py-24 bg-white max-md:px-5">
      <div
        className="flex absolute top-2/4 left-2/4 z-0 max-w-full rounded-full -translate-x-2/4 -translate-y-2/4 h-[597px] min-h-[597px] w-[597px]"
        aria-hidden="true"
      />
      <Header />
      <MainContent />
      <ImageSection />
    </main>
  );
}

export default GetStarted;
