/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex z-0 flex-col items-center w-full max-md:max-w-full">
      <h1 className="text-xl font-semibold leading-snug text-green-600">
        GET STARTED
      </h1>
    </header>
  );
}

export default Header;
