/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ImageSection() {
  return (
    <section className="flex overflow-hidden z-0 gap-2.5 justify-center items-center self-center p-2.5 mt-10 max-w-full w-[748px]">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8c80aa40bd81e362c3be2676c7cda41d10a8985c40ad329be0faecd077503a21?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca"
        alt="Design perfection illustration"
        className="object-contain self-stretch my-auto aspect-[0.46] min-w-[240px] w-[393px]"
      />
    </section>
  );
}

export default ImageSection;
