/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FeatureCard({ icon, title, description, isHighlighted }) {
  const baseClasses =
    "flex overflow-hidden flex-col px-10 py-6 mt-4 w-full rounded-3xl max-w-[592px] max-md:px-5 max-md:max-w-full";
  const highlightedClasses = isHighlighted
    ? "bg-orange-100 border border-amber-500 border-solid"
    : "bg-neutral-100";

  return (
    <div className={`${baseClasses} ${highlightedClasses}`}>
      <div className="flex gap-6 items-center self-start text-lg font-medium leading-tight">
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
        />
        <h2 className="self-stretch my-auto">{title}</h2>
      </div>
      {description && (
        <p className="pl-12 mt-4 w-full text-sm leading-4 max-md:pl-5 max-md:max-w-full">
          {description}
        </p>
      )}
    </div>
  );
}

export default FeatureCard;
