/**
 * This code was generated by Builder.io.
 */
export const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/1749ac2d20728654cae06a65495cb1b1ef0cee7b88e85817dd316946f8fcc2e6?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    title: "Real-time RSVP Tracking",
    description:
      "Instantly see who's coming and going, so you can stay on top of your guest list",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/1820548724d28568987bceae23be3bca30398caf7d07fc76cf3dffb1d086473f?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    title: "Customizable Guest Lists",
    description: "",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/fedb1dd8552519dc8aa1fdf2d295a176b6053ed25f6afcd701d6a95b50c5e4ee?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    title: "Detailed Analytics",
    description: "",
  },
];
