/**
 * This code was generated by Builder.io.
 */
import React from "react";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/cd57b9f1023e654c7a57b72138ab320e3c41024090f2c57c5be9182cbfda6a3a?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    text: "Download the app",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/70d1d41f44e3eb8a299c4c05e9c17b5bcad27cc897d9580d85a801ec4bfac3b4?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    text: "Create an account",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/276ba3b1c61e35532ea03eea27b5313008362e3f491291ef6e2baf7b6f6c7f65?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    text: "Design your Invitation",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c9bcd6ae1e5a64dc3a651893cc1e6afcda335229f4b38a70b420f807f67ac549?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    text: "Publish and share",
  },
];

function FeatureItem({ icon, text }) {
  return (
    <div className="flex overflow-hidden flex-col justify-center items-center self-stretch px-2.5 py-5 my-auto min-h-[120px] min-w-[240px] w-[280px]">
      <img
        loading="lazy"
        src={icon}
        className="object-contain w-12 aspect-square"
        alt=""
      />
      <div className="mt-4">{text}</div>
    </div>
  );
}

function FeatureSection() {
  return (
    <div className="bg-gray-100 flex flex-wrap gap-8 justify-center items-center self-stretch my-auto min-w-4/5 max-md:max-w-full">
      {features.map((feature, index) => (
        <FeatureItem key={index} icon={feature.icon} text={feature.text} />
      ))}
    </div>
  );
}

export default FeatureSection;
