/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FeatureCard({ imageSrc, title, description }) {
  return (
    <div className="flex gap-6 items-start max-w-1/2">
      <img
        loading="lazy"
        src={imageSrc}
        alt=""
        className="object-contain shrink-0 aspect-square w-[120px]"
      />
      <div className="flex gap-2 items-start ">
        <div className="flex flex-col justify-center ">
          <h3 className="text-2xl font-semibold leading-7 text-black">
            {title}
          </h3>
          <p className="mt-2 text-base leading-6 text-zinc-600">
            {description}
          </p>
        </div>
      </div>
    </div>
  );
}

export default FeatureCard;
