/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureCard from "./FeatureCard";

const features = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/882de7fae8e40cdf931e6ae29434f6af797ffa65ba3375f3bbe0bf76210af8a8?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    title: (
      <>
        500+ templates <br /> to choose from
      </>
    ),
    description:
      "Choose from a range of professionally designed templates for various occasions.",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f6ba8d7e8d72f158d3f2da0e2da39c644b05edc86bb9a6b885b7e707262a6e79?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    title: (
      <>
        Less than <br />2 minutes to create
      </>
    ),
    description:
      "Quickly create and customize invitations with our intuitive drag-and-drop editor.",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/32dd402f34e2ec00c09b29abd338a3550c4dc4b59d1cc0d994c99e0739151713?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    title: (
      <>
        Efficient RSVP <br /> Management
      </>
    ),
    description: (
      <>
        Stay organized with up-to-date <br /> RSVP statuses and streamline{" "}
        <br /> your event planning process.
      </>
    ),
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/26717a937764c37e798b049d6095b63450c4cd41c45671d9bc8020a73d2ae5c6?placeholderIfAbsent=true&apiKey=00dd475291cf4f1da724421e257168ca",
    title: (
      <>
        Instant WhatsApp <br /> Distribution
      </>
    ),
    description: (
      <>
        Send invitations directly <br /> via WhatsApp with just a few clicks.{" "}
        <br /> Effortlessly reach your guests
      </>
    ),
  },
];

function FeaturesGrid() {
  return (
    <section className="flex overflow-hidden flex-col justify-center py-24 w-4/5 mx-auto">
      <div className="grid sm:grid-cols-2 gap-10 justify-center items-start max-md:max-w-full">
        {features.map((feature, index) => (
          <FeatureCard key={index} {...feature} />
        ))}
      </div>
    </section>
  );
}

export default FeaturesGrid;
